"""collone Utilisateurs.logo

Revision ID: 8e0b7e9ed718
Revises: cbf66be0272f
Create Date: 2025-12-12 12:03:44.045020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e0b7e9ed718'
down_revision: Union[str, Sequence[str], None] = 'cbf66be0272f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("utilisateurs") as batch_op:
        batch_op.drop_column('logo')
    # ### end Alembic commands ###
