"""collonne_avis_ok

Revision ID: b430f5374ba6
Revises: b1756df9455a
Create Date: 2025-11-21 17:46:29.340921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b430f5374ba6'
down_revision: Union[str, Sequence[str], None] = 'b1756df9455a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avis', sa.Column('ok', sa.Boolean(), nullable=False, server_default=str(1)))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avis') as batch_op:
        batch_op.drop_column('ok')
    # ### end Alembic commands ###
